### ISSUE TITLE
Accessing the queue status when using the Anki algorithm

### ISSUE THREAD

**Issue by eniac314** [SiriusStarr/elm-spaced-repetition#1]
In the documentation for the Anki algorithm you mention that Hard should not be presented as an option when answering cards in the Learning queue. Since the SRSData type is opaque, how can I find out if a card is in the learning queue?

**Comment by SiriusStarr** [comment]
Good catch!  So there's not actually anything *wrong* with presenting `Hard` for a learning-stage card, it's just that it doesn't do anything different at that stage than answering `Again`.  The behavior of bother "learning" and "lapsed" cards is identical, inasmuch as both `Again` and `Hard` reset the card to the first stage, whereas `Good` advances it and `Easy` instantly graduates it to review.  Anki itself I believe only presents 3 buttons for those stages to avoid the false illusion of choice.

So in the short term, nothing wrong with leaving `Hard` as an option.  However, I think it would be good moving forwards to reveal what stage a card is in, as one could imagine wanting to display this information to a user, and it would also allow changing the presentation of the answer buttons.  One option would be to make `getDueCardIndices` return queue status as well, making its signature something like

```elm
type Queue
    = New
    | Learning
    | Reviewing
    | Lapsed

getDueCardIndices : Posix -> Deck a b -> List ( Int, Queue, Bool )
```

The downside to this is its a breaking change, necessitating a major version bump.  Other downside is that it's simply more information that someone might not want to have.

Other option would be to keep `getDueCardIndices` the same and add a new function, like

```elm
type Queue
    = New
    | Learning
    | Reviewing
    | Lapsed

getDueCardIndices : Posix -> Deck a b -> List ( Int, Bool )

getDueCardIndicesAndQueue : Posix -> Deck a b -> List ( Int, Queue, Bool )
```

Which would allow one to choose which they wanted and would be a minor version.
```

**Comment by eniac314** [comment]
I think having the possibility to adapt displayed information and controls to the state of the card would be nice indeed.A new `getDueCardIndicesAndQueue` function would be welcome!
Great work anyway!

**Comment by SiriusStarr** [comment]
Added in 7f71df9574a0050c84b4f077e13c9f978d8985da.  See `getDueCardIndicesWithDetails` to get the detailed queue status and the like for all cards or `getCardDetails` for details on a single card.

Sorry turnaround was slow on that!  Had a lot of demands on my time this past month.
